apiVersion: k3s-pilot.dev/v1alpha1
kind: Machine
metadata:
  name: prod-1

spec:
  connectionRef: prod-1

  k3s:
    state: absent

    uninstall:
      removeData: false
      removeKubeconfig: true

  health:
    require:
      - ssh.available
      - k3s.absent
      - systemd.k3s.absent

  execution:
    mode: transactional
    rollback:
      enabled: true
      on:
        - verifyFailure
